In [13]:
from preparing_data import *
import pandas as pd
from pathlib import Path

In [14]:
limit = 1000
downloader = GetCandles(interval="1h", limit=limit)

parquet_path = Path("history_data.parquet")
if parquet_path.exists():
    old_df = pd.read_parquet(parquet_path)
else:
    old_df = pd.DataFrame()
new_df = pd.DataFrame()
pairs = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "USDCUSDT", "XRPUSDT", "SOLUSDT", "ADAUSDT", "DOGEUSDT", "TRXUSDT", "AVAXUSDT",
    "DOTUSDT", "LINKUSDT", "TONUSDT", "SHIBUSDT", "MATICUSDT", "LTCUSDT", "DAIUSDT", "BCHUSDT", "UNIUSDT", "ICPUSDT",
    "NEARUSDT", "APTUSDT", "FILUSDT", "XLMUSDT", "STXUSDT", "IMXUSDT", "GRTUSDT", "RENDERUSDT", "OPUSDT",
    "SUIUSDT", "ATOMUSDT", "AAVEUSDT", "THETAUSDT", "LDOUSDT", "ALGOUSDT", "FETUSDT", "VETUSDT", "EGLDUSDT", "TIAUSDT",
    "MKRUSDT", "FLOWUSDT", "GALAUSDT", "SANDUSDT", "MANAUSDT", "QNTUSDT", "CHZUSDT", "MINAUSDT", "PEPEUSDT"
]
bad_pairs = []
for pair in pairs:
    try:
        downloader.symbol = pair
        bi = downloader.get_binance_candles().to_dataframe()
        bi["symbol"] = pair
        # display(bi.head())

        new_df = pd.concat([new_df, bi], ignore_index=True)

        print(f"count of {pair}={len(bi)}")
        time.sleep(0.5)

    except Exception as e:
        print(f"skip {pair}: {e}")
        bad_pairs.append(pair)
        time.sleep(1)

df = pd.concat([old_df, new_df], ignore_index=True)
df = df.drop_duplicates(subset=["symbol", "timestamp"], keep="last")
if len(bad_pairs)!=0: print(bad_pairs)

count of BTCUSDT=1000
count of ETHUSDT=1000
count of BNBUSDT=1000
count of USDCUSDT=1000
count of XRPUSDT=1000
count of SOLUSDT=1000
count of ADAUSDT=1000
count of DOGEUSDT=1000
count of TRXUSDT=1000
count of AVAXUSDT=1000
count of DOTUSDT=1000
count of LINKUSDT=1000
count of TONUSDT=801
count of SHIBUSDT=1000
skip MATICUSDT: Binance вернул пустой список свечей для MATICUSDT
count of LTCUSDT=1000
skip DAIUSDT: Binance вернул пустой список свечей для DAIUSDT
count of BCHUSDT=1000
count of UNIUSDT=1000
count of ICPUSDT=1000
count of NEARUSDT=1000
count of APTUSDT=1000
count of FILUSDT=1000
count of XLMUSDT=1000
count of STXUSDT=1000
count of IMXUSDT=1000
count of GRTUSDT=1000
count of RENDERUSDT=1000
count of OPUSDT=1000
count of SUIUSDT=1000
count of ATOMUSDT=1000
count of AAVEUSDT=1000
count of THETAUSDT=1000
count of LDOUSDT=1000
count of ALGOUSDT=1000
count of FETUSDT=1000
count of VETUSDT=1000
count of EGLDUSDT=1000
count of TIAUSDT=1000
skip MKRUSDT: Binance вернул пустой список свечей для MKRUSDT
count of FLOWUSDT=1000
count of GALAUSDT=1000
count of SANDUSDT=1000
count of MANAUSDT=1000
count of QNTUSDT=1000
count of CHZUSDT=1000
count of MINAUSDT=1000
count of PEPEUSDT=1000
['MATICUSDT', 'DAIUSDT', 'MKRUSDT']

In [15]:
new_df["timestamp"] = pd.to_datetime(new_df["timestamp"])
if not old_df.empty:
    old_df["timestamp"] = pd.to_datetime(old_df["timestamp"])
print("самая последняя дата из old_df=",old_df["timestamp"].max())
print("самая первая дата из new_df=", new_df["timestamp"].min())
date_check = (
    df
    .groupby("symbol")
    .agg(
        rows=("timestamp", "count"),
        min_date=("timestamp", "min"),
        max_date=("timestamp", "max"),
    )
    .sort_values("rows")
)

display(date_check)

самая последняя дата из old_df= 2026-07-08 11:00:00
самая первая дата из new_df= 2026-05-27 21:00:00

            rows            min_date            max_date
symbol
TONUSDT     4860 2025-12-09 18:00:00 2026-06-30 05:00:00
AAVEUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
ALGOUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
ADAUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
ATOMUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
AVAXUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
BCHUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
APTUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
BTCUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
CHZUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
DOGEUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
DOTUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
EGLDUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
ETHUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
FETUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
BNBUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
FLOWUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
GALAUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
GRTUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
ICPUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
IMXUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
LDOUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
LINKUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
LTCUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
MANAUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
MINAUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
NEARUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
OPUSDT      5059 2025-12-09 18:00:00 2026-07-08 12:00:00
PEPEUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
QNTUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
RENDERUSDT  5059 2025-12-09 18:00:00 2026-07-08 12:00:00
FILUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
SANDUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
SHIBUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
STXUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
SOLUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
SUIUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
THETAUSDT   5059 2025-12-09 18:00:00 2026-07-08 12:00:00
TIAUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
TRXUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
UNIUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
USDCUSDT    5059 2025-12-09 18:00:00 2026-07-08 12:00:00
VETUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
XLMUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00
XRPUSDT     5059 2025-12-09 18:00:00 2026-07-08 12:00:00

In [16]:
new_df

,timestamp,open,high,low,close,volume,symbol
0,2026-05-27 21:00:00,74860.420000,75032.010000,74663.450000,75026.670000,5.492531e+02,BTCUSDT
1,2026-05-27 22:00:00,75026.670000,75105.170000,74952.360000,75066.080000,8.798020e+02,BTCUSDT
2,2026-05-27 23:00:00,75066.090000,75415.810000,75056.250000,75274.580000,3.894148e+02,BTCUSDT
3,2026-05-28 00:00:00,75274.580000,75274.580000,74341.760000,74473.010000,6.532197e+02,BTCUSDT
4,2026-05-28 01:00:00,74473.010000,74775.500000,74260.910000,74418.130000,6.246411e+02,BTCUSDT
...,...,...,...,...,...,...,...
44796,2026-07-08 08:00:00,0.000003,0.000003,0.000003,0.000003,1.144778e+11,PEPEUSDT
44797,2026-07-08 09:00:00,0.000003,0.000003,0.000003,0.000003,1.765368e+11,PEPEUSDT
44798,2026-07-08 10:00:00,0.000003,0.000003,0.000003,0.000003,2.064745e+11,PEPEUSDT
44799,2026-07-08 11:00:00,0.000003,0.000003,0.000003,0.000003,7.710205e+11,PEPEUSDT
44800,2026-07-08 12:00:00,0.000003,0.000003,0.000003,0.000003,3.784869e+10,PEPEUSDT

In [17]:
parquet_path.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(parquet_path, index=False)