In [1]:
from preparing_data import *
import pandas as pd
from pathlib import Path

In [3]:
limit = 2000
downloader = GetCandles(interval="1h", limit=limit)

parquet_path = Path("history_data.parquet")
if parquet_path.exists():
    old_df = pd.read_parquet(parquet_path)
else:
    old_df = pd.DataFrame()
new_df = pd.DataFrame()
pairs = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "USDCUSDT", "XRPUSDT", "SOLUSDT", "ADAUSDT", "DOGEUSDT", "TRXUSDT", "AVAXUSDT",
    "DOTUSDT", "LINKUSDT", "TONUSDT", "SHIBUSDT", "MATICUSDT", "LTCUSDT", "DAIUSDT", "BCHUSDT", "UNIUSDT", "ICPUSDT",
    "NEARUSDT", "APTUSDT", "FILUSDT", "XLMUSDT", "STXUSDT", "IMXUSDT", "GRTUSDT", "RENDERUSDT", "OPUSDT",
    "SUIUSDT", "ATOMUSDT", "AAVEUSDT", "THETAUSDT", "LDOUSDT", "ALGOUSDT", "FETUSDT", "VETUSDT", "EGLDUSDT", "TIAUSDT",
    "MKRUSDT", "FLOWUSDT", "GALAUSDT", "SANDUSDT", "MANAUSDT", "QNTUSDT", "CHZUSDT", "MINAUSDT", "PEPEUSDT"
]
bad_pairs = []
for pair in pairs:
    try:
        downloader.symbol = pair
        bi = downloader.get_binance_candles().to_dataframe()
        bi["symbol"] = pair
        # display(bi.head())

        new_df = pd.concat([new_df, bi], ignore_index=True)

        print(f"count of {pair}={len(bi)}")
        time.sleep(0.5)

    except Exception as e:
        print(f"skip {pair}: {e}")
        bad_pairs.append(pair)
        time.sleep(1)

df = pd.concat([old_df, new_df], ignore_index=True)
df = df.drop_duplicates(subset=["symbol", "timestamp"], keep="last")
if len(bad_pairs)!=0: print(bad_pairs)

count of BTCUSDT=2000
count of ETHUSDT=2000
count of BNBUSDT=2000
count of USDCUSDT=2000
count of XRPUSDT=2000
count of SOLUSDT=2000
count of ADAUSDT=2000
count of DOGEUSDT=2000
count of TRXUSDT=2000
count of AVAXUSDT=2000
count of DOTUSDT=2000
count of LINKUSDT=2000
count of TONUSDT=1728
count of SHIBUSDT=2000
skip MATICUSDT: Binance вернул пустой список свечей для MATICUSDT
count of LTCUSDT=2000
skip DAIUSDT: Binance вернул пустой список свечей для DAIUSDT
count of BCHUSDT=2000
count of UNIUSDT=2000
count of ICPUSDT=2000
count of NEARUSDT=2000
count of APTUSDT=2000
count of FILUSDT=2000
count of XLMUSDT=2000
count of STXUSDT=2000
count of IMXUSDT=2000
count of GRTUSDT=2000
count of RENDERUSDT=2000
count of OPUSDT=2000
count of SUIUSDT=2000
count of ATOMUSDT=2000
count of AAVEUSDT=2000
count of THETAUSDT=2000
count of LDOUSDT=2000
count of ALGOUSDT=2000
count of FETUSDT=2000
count of VETUSDT=2000
count of EGLDUSDT=2000
count of TIAUSDT=2000
skip MKRUSDT: Binance вернул пустой список свечей для MKRUSDT
count of FLOWUSDT=2000
count of GALAUSDT=2000
count of SANDUSDT=2000
count of MANAUSDT=2000
count of QNTUSDT=2000
count of CHZUSDT=2000
count of MINAUSDT=2000
count of PEPEUSDT=2000
['MATICUSDT', 'DAIUSDT', 'MKRUSDT']

In [4]:
new_df["timestamp"] = pd.to_datetime(new_df["timestamp"])
if not old_df.empty:
    old_df["timestamp"] = pd.to_datetime(old_df["timestamp"])
print("самая последняя дата из old_df=",old_df["timestamp"].max())
print("самая первая дата из new_df=", new_df["timestamp"].min())
date_check = (
    df
    .groupby("symbol")
    .agg(
        rows=("timestamp", "count"),
        min_date=("timestamp", "min"),
        max_date=("timestamp", "max"),
    )
    .sort_values("rows")
)

display(date_check)

самая последняя дата из old_df= 2026-07-08 12:00:00
самая первая дата из new_df= 2026-04-19 06:00:00

            rows            min_date            max_date
symbol
TONUSDT     4860 2025-12-09 18:00:00 2026-06-30 05:00:00
AAVEUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
ALGOUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
ADAUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
ATOMUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
AVAXUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
BCHUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
APTUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
BTCUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
CHZUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
DOGEUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
DOTUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
EGLDUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
ETHUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
FETUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
BNBUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
FLOWUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
GALAUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
GRTUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
ICPUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
IMXUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
LDOUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
LINKUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
LTCUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
MANAUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
MINAUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
NEARUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
OPUSDT      5132 2025-12-09 18:00:00 2026-07-11 13:00:00
PEPEUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
QNTUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
RENDERUSDT  5132 2025-12-09 18:00:00 2026-07-11 13:00:00
FILUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
SANDUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
SHIBUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
STXUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
SOLUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
SUIUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
THETAUSDT   5132 2025-12-09 18:00:00 2026-07-11 13:00:00
TIAUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
TRXUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
UNIUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
USDCUSDT    5132 2025-12-09 18:00:00 2026-07-11 13:00:00
VETUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
XLMUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00
XRPUSDT     5132 2025-12-09 18:00:00 2026-07-11 13:00:00

In [5]:
new_df

,timestamp,open,high,low,close,volume,symbol
0,2026-04-19 06:00:00,75496.010000,75637.440000,75357.000000,75515.770000,1.752880e+02,BTCUSDT
1,2026-04-19 07:00:00,75515.760000,75782.630000,75424.400000,75664.620000,2.946042e+02,BTCUSDT
2,2026-04-19 08:00:00,75664.620000,75687.040000,75516.390000,75545.600000,1.746379e+02,BTCUSDT
3,2026-04-19 09:00:00,75545.600000,75545.600000,75280.920000,75400.090000,3.853159e+02,BTCUSDT
4,2026-04-19 10:00:00,75400.090000,75400.090000,74867.720000,75252.340000,7.716150e+02,BTCUSDT
...,...,...,...,...,...,...,...
89723,2026-07-11 09:00:00,0.000003,0.000003,0.000003,0.000003,5.351143e+10,PEPEUSDT
89724,2026-07-11 10:00:00,0.000003,0.000003,0.000003,0.000003,5.732518e+10,PEPEUSDT
89725,2026-07-11 11:00:00,0.000003,0.000003,0.000003,0.000003,1.115615e+11,PEPEUSDT
89726,2026-07-11 12:00:00,0.000003,0.000003,0.000003,0.000003,3.101513e+11,PEPEUSDT
89727,2026-07-11 13:00:00,0.000003,0.000003,0.000003,0.000003,8.390622e+10,PEPEUSDT

In [6]:
parquet_path.parent.mkdir(parents=True, exist_ok=True)
df.to_parquet(parquet_path, index=False)